### ISSUE TITLE
Verified Plugin

### ISSUE THREAD

**Issue by dsully** [vivienne/homebridge-haiku-senseme#2]
This plugin should be verified via https://github.com/homebridge/verified - everything looks to be in order!

**Comment by DJay-X** [comment]
Hey there. Thanks for you work @vivienne @dsully 
Am I right that this plugin can replace https://github.com/sean9keenan/homebridge-bigAssFans ?
And what are the differences/advantages to do so?

Thanks again.

**Comment by vivienne** [comment]
> Hey there. Thanks for you work @vivienne @dsully
> Am I right that this plugin can replace https://github.com/sean9keenan/homebridge-bigAssFans ?
> And what are the differences/advantages to do so?
> 
> Thanks again.

@DJay-X I think it can be used to replace the [homebridge-bigAssFans](https://github.com/sean9keenan/homebridge-bigAssFans) plugin, but haven't tested it myself. I wrote this plugin because I have only the Haiku lights and not their fan, and because the discovery function in the other plugin just didn't work for me when I tried it. 

The main difference is the API that this plugin is built on - I used a modified version of the [haiku-senseme](https://github.com/vivienne/haiku-senseme) API. It also creates a different Accessory based on the type of device identified (a light, or a fan). Lastly, when I was trying to find a plugin for my Haiku lights that would work, it seemed that all of the packages had not been updated for a while. - which may be why the plugins wouldn't work for me. This plugin was built with updated dependencies. 

IMO if the other plugin is working solidly for you, there's no reason to switch over. But if you want to give this one a try and contribute or provide feedback that would be nice too. After using it in my own home for several weeks I've found that sometimes the devices become unresponsive but haven't spent much time looking into it yet.

**Comment by dsully** [comment]
From my point of view, this is a much more modern and readable plugin due to how the code is written in the haiku-senseme package, as an observable and being data-driven for constructing the objects (via commands.json).

For the platform itself, the benefits of TypeScript and being based off the homebridge-plugin-template once again makes it easier to make changes and to understand the logic compared to the other plugin.

It also appears that Sean has abandoned his repo, which doesn't help either.

**Comment by vivienne** [comment]
> This plugin should be verified via https://github.com/homebridge/verified - everything looks to be in order!

Thanks Dan for the push.. I've opened an [issue](https://github.com/homebridge/verified/issues/193) to get the plugin verified.

**Comment by DJay-X** [comment]
Hi Guys..
Unfortunately our plugin didn't work for me. I removed "the old" BAF in config.json and added yours by config-ui-ix.

```
{
            "name": "Deckenventilator",
            "platform": "haiku"
        }
```

After homebridge restart no Fan is showing up at all. 
I hope you are able to fix this. Would love to switch to your plugin. 
Thanks in advance.

Product Code K3127-S0-PW-09-02-C-01
Product Name Haiku Ceiling Fan, I Series, 52 Inches, Low Profile Mount,
White Airfoils, White Motor, (<125W), ( CZ, **GER**, IT ), (U), 0.019HP, 100-125, 200-240 VAC, Single Phase

![Napkin 07 10 20, 9 53 05 AM](https://user-images.githubusercontent.com/3874239/95303001-f38ff280-0882-11eb-82cd-d9d4a4ba28e4.png)


```
Okt 07 09:45:50 raspberrypi-3BPlus homebridge[24862]: [2020-10-7 9:45:50] [Deckenventilator] Found a device: Ventilator / FAN,HAIKU,HSERIES / 192.168.178.32 / 20:F8:5E:F6:C0:82
Okt 07 09:45:50 raspberrypi-3BPlus homebridge[24862]: [2020-10-7 9:45:50] [Deckenventilator] Not sure what to do with this device type: Ventilator (FAN,HAIKU,HSERIES)
Okt 07 09:46:10 raspberrypi-3BPlus homebridge[24862]: SenseME discovery server shutting down
```

**Comment by dsully** [comment]
@DJay-X Can you create a separate issue for that problem? Thanks

**Comment by vivienne** [comment]
The plugin is now verified, closing this issue.
